# Generated by Django 4.0.4 on 2023-01-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saldoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialsaldo',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saldoapp.initialsaldo')),
            ],
            options={
                'unique_together': {('saldo_id', 'year', 'month')},
            },
        ),
    ]
