# Generated by Django 4.0.4 on 2023-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saldoapp', '0002_alter_initialsaldo_value_alter_payment_value_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsaldo',
            name='year',
            field=models.PositiveIntegerField(default=2017),
            preserve_default=False,
        ),
    ]
