# Generated by Django 4.0.4 on 2023-01-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saldoapp', '0003_initialsaldo_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='initialsaldo',
            unique_together={('apartment_id', 'year')},
        ),
    ]
