# Generated by Django 4.0.4 on 2023-01-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saldoapp', '0004_alter_initialsaldo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='initialsaldo',
            unique_together=set(),
        ),
    ]
